strand1='TGTGCCTTAAAGCGTACCCTGGAACGATCCAAAGGCTGGCACGAGCGTAACCCTTCCTCATCTCCTTGGAAACGTAACTTTGCCCATTCCGTTCCATACAAGAATTCTCCGAGGCTAAAGTCCACGTGAATCCCGTTCAACAGTGGGAAAGGTGTGGCTTTCTGGGAGCCCGCACCCTTGTCGAAGTTCAACCTAGGGCCCGCCAAATCATTTATCTCTGACCTGGGCCTGTTCAGGTCGTACGTCGAGTACCTCAATCGCCGAGACTGGTGGGGCAATCCGATATAACGTTCATTTCCTGTGAGGGGCTACTCAAATATGATTCTTCAAGGGTTGCGAGATCTGGCATCTTAATGCGCATGACGTCGTTCTCATCCTACACCTGTCAAGGACCTTACAAGCAAATCAACTTGTTGAGTCAGAGTAAATGGTTCCACGTCCTTCCCGCCGGTAGCTGAGCCCGACTTTGTCGTAGCAGGGGCACCGCTGGTCGCCCAGGGTTTTAGTTACGCTTTCCTGAAGTATAGAGTCACTGTTGATGGCCTTTAAATTCACAATCTATCGGGGTCCGCTATTTTGTCCAATAAACGGACGCCGCGGATCAGCGTACGCGGGGTTCAACGAAGCCCGCTTTAGTACCGAACGAAGCTATACCAGCGATGGAACGCGTACTCGGTAAGTTACCCTAATCCCCAGGATAGAATTGCTCCTAGTGCACATCACAACAAGATATGATACTCCGGCATACGCCCGACCTGGTCTAGTCCCCTGGAGGCTTTATCTCACAATAATCAGCGAATGGGTCGTGGATGAGCAGTCCAATTATCAACATACGTCTCGGACCGGTA'
strand2='AGTGCTTTAAGGCATAATTTAAAAGCACCCGAGAGTTGGCTCGACCGTGACCCTTTCTCACTGCTTCGAATATGTAACTTCGCCTAATTCCATCCGTATCAGAATCCTCCGAAACGAAATTCCCCGTGTGTCACGTTTAATAGTACGAAAGGTGTGGTTGACCGGAAGCCTGCACCCGTGCCATAGCTCAACTAAAAGCCCGCCAGACCATCTCCCCCTCACTAAAGCACGTTCAGATCGTACGTCGGGTGCCTTGACCACCGAAGATAGTAAGCTAATCGAGTGCAACGTCCATCCTGTGTGAGGTGTTATCCAAGAGCGATCCCGCAGTGGTCGAACCAGCTGGCATGACGAGGCGCCTAATGTCCTCTTCGTTCTGCGCCCATCAGTGAACTTACAAGCAAATCGACTTGTCGAGTCAGTGTGAGTAGCCCAACCTTTCTTCCACCGGTAGCTGAGCCCCACTTCGCCGCAGCAGGAGCAGCACTGAGCGCTCAAGGTTTCATTGACGCTTTCCTGGAGTATAGAGTCACGGTTAATTGCCTTTGAATTCTCAATTCATCGGGGTCTACCATTTTGCCTGATGCACGGATACGTTAGACTATCTTCTGCGGGGGTAGGCGGAGCCCACTTTAGTGCTAAAAGAGACTATACCAAAGGGTGAGTTAGGACCCGCCAGGTCACTCTAATCCCCATGATAGACTTGTTCCCGATGAACATCATGGTAAGGTCTACCGTTTCAGCTTACCCCAAATCTGATCTAGTCCTTCATAGGCTTCATTTTACGATATCCGGCGGTTGTGTCGTGAGCGGGAAGTCAGATTATTGATATGCGTCGCCGATCGTCA'


def tran(strand1,strand2):
    transt = 0
    transv = 0
    for ch1, ch2 in zip(strand1, strand2):
        if ch1 == ch2:
            continue
        elif ch1 != ch2:
            if ch1 == 'A' and ch2 == 'G':
                 transt += 1
            elif ch1 == 'G' and ch2 == 'A':
                transt += 1
            elif ch1 == 'T' and ch2 == 'C':
                transt += 1
            elif ch1 == 'C' and ch2 == 'T':
                transt += 1
            elif ch1 == 'A' and (ch2 == 'T' or ch2 == 'C'):
                 transv += 1
            elif ch1 == 'T' and (ch2 == 'A' or ch2 == 'G'):
                 transv += 1
            elif ch1 == 'G' and (ch2 == 'C' or ch2 == 'T'):
                 transv += 1
            elif ch1 == 'C' and (ch2 == 'G' or ch2 == 'A'):
                 transv += 1
    
    return (round((transt/transv),11))
    
    
print(tran(strand1,strand2))
